# Generated by Django 3.0.5 on 2020-05-16 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtable',
            old_name='description',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='blogtable',
            name='title',
        ),
        migrations.AddField(
            model_name='blogtable',
            name='Author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='Image',
            field=models.FileField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='Title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
