# Generated by Django 3.0.5 on 2020-05-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200516_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtable',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
